# Generated by Django 5.1 on 2024-08-13 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(help_text='The text must be unique', max_length=128, unique_for_month='published_at')),
                ('slug', models.CharField(max_length=128, unique_for_month='published_at')),
                ('status', models.IntegerField(choices=[(1, 'Send'), (2, 'Cancel')], default=2)),
                ('subject', models.TextField(max_length=125)),
                ('content', models.TextField(blank=True, max_length=225, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
