# Generated by Django 5.1 on 2024-08-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=125)),
                ('slug', models.CharField(max_length=125)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'verbose_name': 'services',
                'verbose_name_plural': 'service',
                'ordering': ['subject'],
                'get_latest_by': ['-published_at'],
            },
        ),
    ]
