# Generated by Django 5.1 on 2024-08-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'get_latest_by': ['-published_at'], 'ordering': ['title'], 'verbose_name': 'services', 'verbose_name_plural': 'service'},
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='subject',
            field=models.CharField(max_length=125),
        ),
    ]
