# Generated by Django 5.1 on 2024-08-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_about_skills_alter_about_options_delete_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='position',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='position1',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='position2',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='position3',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='position4',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='position5',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
