# Generated by Django 5.1 on 2024-08-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_position_about_position1_about_position2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='video',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
