# Generated by Django 5.1 on 2024-08-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_about_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
