# Generated by Django 5.1 on 2024-08-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=125)),
                ('slug', models.CharField(max_length=125)),
                ('content', models.CharField(max_length=500)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('web_site', models.URLField(blank=True, null=True)),
                ('author', models.CharField(max_length=125)),
                ('author_about', models.CharField(max_length=225)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('author_position', models.CharField(blank=True, max_length=125, null=True)),
            ],
            options={
                'verbose_name': 'work',
                'verbose_name_plural': 'works',
            },
        ),
    ]
